### ISSUE TITLE
[Proposal] Drop support for Symfony 2.6 and older

### ISSUE THREAD

**Issue by stof** [xabbuh/PandaBundle#20]
I'm currently working on updating the bundle for https://github.com/xabbuh/panda-client/pull/16

The DI extension has lots of code dealing with the old way to configure a factory for a service (half of the services of the bundle have a factory). If we were dropping support for Symfony 2.3 to 2.5, we could move back the factory to the XML file, making things much more readable. I would then also drop support for 2.6 which is EOLed.

Among this versions, 2.4, 2.5 and 2.6 are EOLed since long. And the 2.3 LTS version is EOMed since nearly 1 year and will reach EOL (i.e. end of security fixes) at the end of May. So IMO, it is fine to stop supporting them.

What do you think @xabbuh ?

**Comment by xabbuh** [comment]
👍 I am all in for dropping support for Symfony versions before 2.7

**Comment by xabbuh** [comment]
see #25
