### ISSUE TITLE
Release 1.5.0

### ISSUE THREAD

**Issue by stof** [xabbuh/PandaBundle#45]
The [diff since the latest release](https://github.com/xabbuh/PandaBundle/compare/v1.4.1...master) (1.4.1) contains fixes for a bunch of deprecations. It even has the changelog for 1.5.0. but the release has not been tagged.

**Comment by xabbuh** [comment]
@stof I have merged a couple of changes. Can you confirm that the bundle still behaves as before? I would then tag a new release this weekend.

**Comment by stof** [comment]
@xabbuh my own project does not use the full feature-set of the bundle. I'm only using `CloudInterface::encodeVideoByUrl` and the notify endpoint. So I won't be able to validate everything.

Thus, my project is still on 3.4 for now (the migration to 4.x is in progress but not done) which will make it harder to test.

**Comment by xabbuh** [comment]
I don't think anybody else is using the bundle, but if someone does they will complain if something breaks. 🤷‍♂
